### ISSUE TITLE
Unknown error pls fix (Error in Console from Proxy)

### ISSUE THREAD

**Issue by Juflos** [TimoCloud/TimoCloud-6.0#10]
19:12:41 [SEVERE] [TimoCloud]  §cError while parsing JSON message: {"t":48,"eT":"B_AVAILABLE_RAM_CHANGE","d":"{\"id\":\"eB9Ycg\",\"oV\":43662,\"nV\":43657}"}
19:12:41 [INFO] Listening on /0.0.0.0:25565
19:12:41 [SEVERE] [TimoCloud]  §cjava.lang.NoClassDefFoundError: cloud/timo/TimoCloud/api/events/ServerRegisterEvent
19:12:41 [SEVERE] [TimoCloud]  §c  at java.lang.Class.getDeclaredMethods0(Native Method)
19:12:41 [SEVERE] [TimoCloud]  §c  at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
19:12:41 [SEVERE] [TimoCloud]  §c  at java.lang.Class.getDeclaredMethods(Class.java:1975)
19:12:41 [SEVERE] [TimoCloud]  §c  at cloud.timo.TimoCloud.api.implementations.managers.EventManager.fireEvent(EventManager.java:39)
19:12:41 [SEVERE] [TimoCloud]  §c  at cloud.timo.TimoCloud.api.implementations.managers.EventManager.callEvent(EventManager.java:33)
19:12:41 [SEVERE] [TimoCloud]  §c  at cloud.timo.TimoCloud.bungeecord.sockets.BungeeStringHandler.handleMessage(BungeeStringHandler.java:44)
19:12:41 [SEVERE] [TimoCloud]  §c  at cloud.timo.TimoCloud.common.sockets.BasicStringHandler.channelRead0(BasicStringHandler.java:15)
19:12:41 [SEVERE] [TimoCloud]  §c  at cloud.timo.TimoCloud.common.sockets.BasicStringHandler.channelRead0(BasicStringHandler.java:9)
19:12:41 [SEVERE] [TimoCloud]  §c  at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
19:12:41 [SEVERE] [TimoCloud]  §c  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
19:12:41 [SEVERE] [TimoCloud]  §c  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
19:12:41 [SEVERE] [TimoCloud]  §c  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
19:12:41 [SEVERE] [TimoCloud]  §c  at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
19:12:41 [SEVERE] [TimoCloud]  §c  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
19:12:41 [SEVERE] [TimoCloud]  §c  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
19:12:41 [SEVERE] [TimoCloud]  §c  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
19:12:41 [SEVERE] [TimoCloud]  §c  at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:321)
19:12:41 [SEVERE] [TimoCloud]  §c  at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:295)
19:12:41 [SEVERE] [TimoCloud]  §c  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
19:12:41 [SEVERE] [TimoCloud]  §c  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
19:12:41 [SEVERE] [TimoCloud]  §c  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
19:12:41 [SEVERE] [TimoCloud]  §c  at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:321)
19:12:41 [SEVERE] [TimoCloud]  §c  at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:295)
19:12:41 [SEVERE] [TimoCloud]  §c  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
19:12:41 [SEVERE] [TimoCloud]  §c  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
19:12:41 [SEVERE] [TimoCloud]  §c  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
19:12:41 [SEVERE] [TimoCloud]  §c  at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
19:12:41 [SEVERE] [TimoCloud]  §c  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
19:12:41 [SEVERE] [TimoCloud]  §c  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
19:12:41 [SEVERE] [TimoCloud]  §c  at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
19:12:41 [SEVERE] [TimoCloud]  §c  at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792)
19:12:41 [SEVERE] [TimoCloud]  §c  at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475)
19:12:41 [SEVERE] [TimoCloud]  §c  at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
19:12:41 [SEVERE] [TimoCloud]  §c  at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
19:12:41 [SEVERE] [TimoCloud]  §c  at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
19:12:41 [SEVERE] [TimoCloud]  §c  at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
19:12:41 [SEVERE] [TimoCloud]  §c  at java.lang.Thread.run(Thread.java:748)
19:12:41 [SEVERE] [TimoCloud]  §cCaused by: java.lang.ClassNotFoundException: cloud.timo.TimoCloud.api.events.ServerRegisterEvent
19:12:41 [SEVERE] [TimoCloud]  §c  at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:63)
19:12:41 [SEVERE] [TimoCloud]  §c  at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:37)
19:12:41 [SEVERE] [TimoCloud]  §c  at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
19:12:41 [SEVERE] [TimoCloud]  §c  ... 37 more

**Comment by TimoZikeli** [comment]
Did you change the `TimoCloud.jar` in your BungeeCord folder while the system was running? Or did you reload the plugin?
If not, please reopen the issue.
