### ISSUE TITLE
Fehler beim Löschen der Temporary-Dateien

### ISSUE THREAD

**Issue by JeyVDW** [TimoCloud/TimoCloud-6.0#17]
**Describe the bug**
Der Fehler kommt irgendwann in der Konsole von der Base. Ich benutze die TimoCloud-6.0-beta-1.5. So wie es aussieht, möchte TimoCloud etwas von Intave löschen. Dieser Ordner müsste eigentlich da sein, ist es aber nicht mehr (weil TimoCloud diesen schon gelöscht hat nach x Minuten).

**To Reproduce**
Der Fehler kam irgendwann und ich habe nichts selber gemacht. Man könnte einen Server löschen und gucken, ob der Fehler dort wieder auftaucht (bei mir ist das nicht der Fall).

**Screenshots**
http://prntscr.com/sfjfph

**Stacktrace**
https://paste.timo.cloud/ewahaxowav.cs

**Configs**
Die Dateien sind leer.

**Operating System (please complete the following information):**
 - OS: Debian
 - Version 10

**Comment by meerpaluten** [comment]
Dies ist nur ein Temporärer fehler, ich konnte ihn leider nicht Reproduce.
