### ISSUE TITLE
Total players online wird nicht richtig angezeigt

### ISSUE THREAD

**Issue by JeyVDW** [TimoCloud/TimoCloud-6.0#23]
**Describe the bug**
Wenn man die Beschreibung von unten befolgt, kommt dort `Total players online: 1`, obwohl insgesamt 2 Spieler auf dem Server sind.

**To Reproduce**
1. Starte mindestens 2 Proxys (bei mir 2 verschiedene Gruppen)
2. Betritt beide Proxys (mit unterschiedlichen Accounts)
3. Gib /glist als Spieler mit dem Recht `bungeecord.command.list` ein

**Stacktrace**
Keine Fehler o.ä. da.

**Operating System (please complete the following information):**
 - OS: [Debian]
 - Version [10 Buster] (bei [Necror ](https://necror.de) gehostet)

**Comment by Lasergott** [comment]
Kannst du das mal mit mehreren Spielern (< 3) testen?

**Comment by JeyVDW** [comment]
kommt das selbe bei raus
