### ISSUE TITLE
Static Server immer vom Global Ordner updaten lassen

### ISSUE THREAD

**Issue by JeyVDW** [TimoCloud/TimoCloud-6.0#27]
**Describe your idea**
Wenn ich etwas im Global Ordner verändere, soll diese Veränderung auch direkt auf jedem Static Server durchgeführt werden.

**Additional context**
Eventuell auch eine Einstellung, bei welchem Server diese Funktion wirken soll.

**Comment by meerpaluten** [comment]
Wird sie doch beim restarten, ich hatte einmal wegen dem löschen gefragt, da meinte Timo das dies nicht gemacht wird da TimoCloud nichts löscht. (Die aussage habe ich auch nicht ganz verstanden, weil du ja die jar aus dem order löscht)

**Comment by TimoZikeli** [comment]
Dateien, die ursprünglich von TimoCloud vom Global- in den Static-Ordner kopiert wurden, werden auch geändert, wenn sie sich im Global ändern (aber nicht, wenn du sie ursprünglich selbst reinkopiert hast). Das gleiche sollte fürs Löschen gelten.

Wenn du die Datei selbst reinkopiert hast, kannst du sie löschen und sie von TimoCloud reinkopieren lassen.
