### ISSUE TITLE
Fehler bei (häufigen) Restart von Servern

### ISSUE THREAD

**Issue by TurtleSkills** [TimoCloud/TimoCloud-6.0#28]
**Describe the bug**
Ich bin momentan ein Plugin auf einem (static-)Server der Cloud am testen (Ich weiß nicht, ob es relevant ist, dass es ein static Server ist). Deshalb wird dieser öfters neugestartet. Nach einiger Zeit kommt ein Fehler beim Neustart des Servers in der Bungeecord-Konsole. _Ich glaube, dass etwas mit dem Registrieren des Servers nicht ganz funktioniert._

**To Reproduce**
Nach vielen Neustarts des Servers kommt ein Fehler (während dieses Neustarts) in der BungeeCord-Konsole.

**Expected behavior**
Der Server solllte eigentlich nur neustarten und man kann danach wieder diesen betreten.

**Stacktrace**
Zuerst kommt dieser Fehler: https://paste.timo.cloud/xuqayudoti.makefile
und kurz danach auch dieser: https://paste.timo.cloud/edemabavel.makefile.

**Operating System:**
 - OS: Linux
 - Version Debian 10

**Comment by Lasergott** [comment]
The bug has already been fixed.
