### ISSUE TITLE
NullPointerException on startup

### ISSUE THREAD

**Issue by constantinDev** [TimoCloud/TimoCloud-6.0#36]
**Describe the bug**
Basically its a NullPointerException while the server starts.

**To Reproduce**
1. Server
2. When the server starts or is in a After-Reload phase
3. Just while starting

**Expected behavior**
It shouldnt print a big stacktrace and should start normally

**Screenshots**
![image](https://user-images.githubusercontent.com/52085196/85208071-d06e2100-b32d-11ea-8d84-613d39422aa6.png)

**Stacktrace**
(Closed console tab, stacktrace in screenshot. Main source in cloud.timo.TimoCloud.bukkit.TimoCloudBukkit.getTemporaryDirectory(TimoCloudBukkit.java:212))

**Configs**
-

**Operating System (please complete the following information):**
 - OS: Windows 10
 - Version: 1909

**Additional context**
The line that causes this seems to be this one:
`return new File(System.getProperty("timocloud-temporarydirectory"));`
in cloud.timo.TimoCloud.bukkit.TimoCloudBukkit.java at line 212

**Comment by Lasergott** [comment]
This is not a mistake. You are using the wrong operating system.
TimoCloud does not support Windows.

**//close**
