### ISSUE TITLE
[Minor] Max player count change - InvocationTargetException

### ISSUE THREAD

**Issue by z609** [TimoCloud/TimoCloud-6.0#6]
**Describe the bug**
This stacktrace occurs when the max player count of a ServerObject is changed (I suppose) unexpectedly - as I was able to read so very carefully through the stacktrace. This stacktrace appears on Spigot servers and on Bungee servers/proxies ONLY - NOT on the core or any base(s).

**To Reproduce**
1. Change the max player count via NMS or similar (read the bottom of page for sample code that can be used to reproduce the issue)
2. Check the log file or active screen session of a Proxy or Spigot server

**Expected behavior**
There don't appear to be any issues after the stacktrace, and the server continues to run normally. Perhaps TimoCloud doesn't expect the amount to change - but some dynamic servers require the max player count to change.

**Screenshots**

**Stacktrace**
[https://hastebin.com/nanogelebu.log](https://hastebin.com/nanogelebu.log)

**Configs**
serverGroups.json: [https://hastebin.com/dayurequra.json](https://hastebin.com/dayurequra.json)

**Operating System (please complete the following information):**
CentOS 6.10 (Final) - shipped with Soyoustart dedicated servers

**Additional context**
The method I am using to change the max player count: [https://hastebin.com/azomukitoq.java](https://hastebin.com/azomukitoq.java)

**Comment by meerpaluten** [comment]
Just for info, but the hastebins are empty.
