### ISSUE TITLE
Cloud Async forwarding to Lobby Error

### ISSUE THREAD

**Issue by JavaMeme** [TimoCloud/TimoCloud-6.0#62]
**Describe the bug**
Every second connect, I will kick from the Server because it's saying that no Lobby was found.

**To Reproduce**
1. Proxy
2. With every second connect
3. Because the Cloud is Async and its to low for forwarding to Lobby

**Stacktrace**
16:46:56 [SEVERE] [TimoCloud]  No lobby server found.
16:46:56 [INFO] [JavaMeme] disconnected with: We are sorry, but we could not find a suitable server to connect you to.

**Operating System (please complete the following information):**
 - Ubuntu
 - 16.04.7

**Comment by Lasergott** [comment]
Hallo,
meinst du das bei einem schnellen Rejoin kein Lobby Server gefunden wird?

**Comment by JavaMeme** [comment]
Ja genau :D

**Comment by meerpaluten** [comment]
Hey, dies ist kein Fehler von TimoCloud! Der Fehler liegt an Bungeecord. Das ServerKickEvent wird auch gecalled wenn der Spieler Disconnected.
